[build]
  publish = "."

[[headers]]
  for = "/outils/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Cache-Control = "no-store"

[[redirects]]
  from = "/praticien"
  to = "/outils/index.html"
  status = 200

[[redirects]]
  from = "/reservation"
  to = "/reservation.html"
  status = 200

[[redirects]]
  from = "/programmes"
  to = "/programmes.html"
  status = 200
