/* ==========================================================================
   A VITA SERENA — Base de données Aromathérapie (huiles essentielles,
   huiles végétales, hydrolats) pour intégration au générateur PHV.
   Source : synthèse et reformulation à partir de "Mon herbier aromatique"
   (55 huiles essentielles, 15 huiles végétales, 6 hydrolats).
   Champs volontairement concis et structurés pour :
     1) le filtrage de sécurité automatique (voir aromatherapieFiltrer())
     2) l'affichage systématique des contre-indications au praticien/cliente
   ATTENTION : ceci n'est pas un substitut à la lecture des fiches complètes
   du livre — en cas de doute, consulter la fiche source ou un pharmacien.
   ========================================================================== */

const HUILES_ESSENTIELLES = [
 {id:"eucalyptus_citronne", nom:"Eucalyptus citronné", latin:"Eucalyptus citriodora", proprietes:["anti-inflammatoire","antispasmodique","antalgique","calmante"], indications:["rhumatismes","tendinite","anxiete","troubles_sommeil","piqures_insectes"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Toujours diluer avant application cutanée (1-5%)."},
 {id:"estragon", nom:"Estragon", latin:"Artemisia dracunculus", proprietes:["digestive","antispasmodique","antiallergique"], indications:["troubles_digestifs","aerophagie","hoquet","allergies_respiratoires","douleurs_regles"], age_min:18, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", vigilance_pro:true}, precaution:"Voie orale réservée à l'adulte, courte durée, faible dose."},
 {id:"epinette_noire", nom:"Épinette noire", latin:"Picea mariana", proprietes:["antifatigue","anti-inflammatoire","antispasmodique"], indications:["epuisement","burnout","fatigue_nerveuse","spasmes"], age_min:18, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"NE JAMAIS utiliser pure sur la peau — toujours diluée dans une huile végétale. Réservée à l'adulte."},
 {id:"encens", nom:"Encens (oliban)", latin:"Boswellia sacra", proprietes:["expectorante","antiseptique","calmante","cicatrisante"], indications:["rhume","angoisse","rhumatismes","migraines","peaux_seches"], age_min:7, ci:{grossesse:true, allaitement:true, asthme:"avis_allergologue"}, precaution:"Diluer avant application cutanée."},
 {id:"cypres", nom:"Cyprès", latin:"Cupressus sempervirens", proprietes:["antitussif","decongestionnant_veineux","oestrogene_mimetique"], indications:["toux","jambes_lourdes","regles_douloureuses","bouffees_chaleur","hemorroides"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", cancer_hormonodependant:true, mastose:true, insuffisance_renale:true}, precaution:"Toujours diluée sur la peau ; voie orale sur avis pharmacien/médecin. Cancer hormono-dépendant = exclusion stricte."},
 {id:"citronnelle_java", nom:"Citronnelle de Java", latin:"Cymbopogon winterianus", proprietes:["antimoustique","anti-infectieuse","drainante"], indications:["piqures_insectes","mycose_cutanee","oedeme"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Diluer si application sur grande surface."},
 {id:"citron", nom:"Citron", latin:"Citrus limon", proprietes:["tonique_hepatique","antinauseeuse","assainissante"], indications:["fatigue_hepatique","jambes_lourdes","mauvaise_haleine","defenses_naturelles"], age_min:7, ci:{grossesse:true, allaitement:true, asthme:"avis_allergologue", insuffisance_renale:true, insuffisance_hepatique:true}, photosensibilisant:true, precaution:"PHOTOSENSIBILISANTE : ne jamais exposer la zone au soleil pendant 24h après application ou prise orale."},
 {id:"ciste_ladanifere", nom:"Ciste ladanifère", latin:"Cistus ladaniferus", proprietes:["cicatrisante","hemostatique","astringente"], indications:["saignement_nez","cicatrices","defenses_naturelles","maladies_infantiles"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", anticoagulants:true}, precaution:"À éviter en cas de traitement anticoagulant. Voie orale réservée à l'adulte sur avis médical."},
 {id:"cedre_atlas", nom:"Cèdre de l'Atlas", latin:"Cedrus atlantica", proprietes:["lipolytique","decongestionnant_circulatoire","mucolytique"], indications:["cellulite","toux_grasse","chute_cheveux","cuir_chevelu"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Ne pas utiliser à forte dose ni sur période prolongée. Inhalation sèche limitée à 5 minutes."},
 {id:"cannelle_ceylan", nom:"Cannelle de Ceylan (écorces)", latin:"Cinnamomum verum", proprietes:["antiseptique_majeure","antivirale","antiparasitaire"], indications:["infections_urinaires","diarrhee","fatigue","spasmes"], age_min:12, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Très irritante pure : dilution impérative à 1% max sur la peau. Voie orale à partir de 12 ans."},
 {id:"camomille_romaine", nom:"Camomille romaine", latin:"Chamaemelum nobile", proprietes:["calmante","antispasmodique","anti-inflammatoire"], indications:["angoisse","troubles_sommeil","migraines","digestion_lente","demangeaisons"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Bien tolérée mais odeur puissante."},
 {id:"bois_ho", nom:"Bois de Hô", latin:"Cinnamomum camphora linaloliferum", proprietes:["cicatrisante","anti-infectieuse","antispasmodique"], indications:["rides","vergetures","acne","convalescence"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Très bien tolérée, alternative au bois de rose protégé."},
 {id:"bergamote", nom:"Bergamote (sans bergaptène)", latin:"Citrus aurantium ssp bergamia", proprietes:["anxiolytique","antiseptique_aerienne","digestive"], indications:["stress","sevrage_tabac_alcool","cheveux_gras"], age_min:15, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Réservée à partir de 15 ans. Éviter le soleil après application même sans bergaptène (par prudence)."},
 {id:"basilic_exotique", nom:"Basilic exotique", latin:"Ocimum basilicum", proprietes:["antispasmodique","regulatrice_nerveuse","tonique_digestive"], indications:["regles_douloureuses","spasmes","fatigue_nerveuse","troubles_sommeil"], age_min:18, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", vigilance_pro:true, insuffisance_hepatique:true}, precaution:"Voie orale adulte, courte durée, faible dose. Diluer largement sur la peau."},
 {id:"eucalyptus_globuleux", nom:"Eucalyptus globuleux", latin:"Eucalyptus globulus", proprietes:["expectorante","mucolytique","antiseptique"], indications:["toux_grasse","bronchite","rhume","infections_urinaires"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", anticoagulants:true}, precaution:"Diluer à 50% pour les enfants."},
 {id:"neroli", nom:"Néroli (fleurs fraîches)", latin:"Citrus aurantium L. ssp amara (fl.)", proprietes:["equilibrante","calmante","relaxante"], indications:["emotivite","anxiete","fatigue_mentale","peau_terne"], age_min:18, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", cancer_hormonodependant:true, mastose:true, hypertension:true}, precaution:"Contre-indiquée avant 18 ans."},
 {id:"myrte_rouge", nom:"Myrte (rouge)", latin:"Myrtus communis", proprietes:["antiseptique","astringente","antitussif"], indications:["hemorroides","varices","bronchite","rhume_des_foins"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"—"},
 {id:"menthe_poivree", nom:"Menthe poivrée", latin:"Mentha x piperita", proprietes:["antalgique","tonifiante","antinauseeuse","anti-infectieuse"], indications:["mal_de_tete","migraine","digestion","demangeaisons","sinusite"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", troubles_cardiovasculaires:true, homeopathie_incompatible:true}, precaution:"Voie orale réservée à 15 ans+. Max 1-2 gouttes sur la peau (effet froid intense). Respecter 3-4h avec un traitement homéopathique."},
 {id:"marjolaine_coquilles", nom:"Marjolaine à coquilles", latin:"Origanum majorana", proprietes:["apaisante","anti-infectieuse","antispasmodique"], indications:["anxiete","tabac","douleurs_digestives","hypertension_benigne"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true}, precaution:"Ne pas appliquer pure, diluer à 50%."},
 {id:"mandarine_verte", nom:"Mandarine verte", latin:"Citrus reticulata blanco", proprietes:["relaxante","sedative","antinauseeuse"], indications:["angoisses","insomnie","dyspepsie","vieillissement_peau"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true, insuffisance_hepatique:true}, photosensibilisant:true, precaution:"PHOTOSENSIBILISANTE : ne pas s'exposer au soleil après usage."},
 {id:"litsee_citronnee", nom:"Litsée citronnée", latin:"Litsea cubeba", proprietes:["relaxante","antivirale","antibacterienne"], indications:["reveils_nocturnes","deprime_passagere","acne","optimisme"], age_min:18, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Réservée à l'adulte, toujours diluée à 5%."},
 {id:"lentisque_pistachier", nom:"Lentisque pistachier", latin:"Pistacia lentiscus", proprietes:["decongestionnant_veineux","hemostatique"], indications:["varices","hemorroides","jambes_lourdes","saignement_nez"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true}, precaution:"Diluer avant application ; à diffuser hors présence de jeunes enfants."},
 {id:"lemongrass", nom:"Lemongrass", latin:"Cymbopogon citratus", proprietes:["calmante","sedative","vasodilatatrice"], indications:["troubles_sommeil","anxiete","jambes_lourdes","antipelliculaire"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Diluer à 5% avant application cutanée."},
 {id:"lavandin_super", nom:"Lavandin super", latin:"Lavandula angustifolia x latifolia", proprietes:["relaxante","spasmolytique","antalgique"], indications:["stress","contractures","crampes","antimoustique"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", troubles_cardiovasculaires:true}, precaution:"Diffusion hors présence de jeunes enfants (contient du camphre)."},
 {id:"lavande_vraie", nom:"Lavande vraie", latin:"Lavandula angustifolia", proprietes:["calmante","antiseptique","relaxante_musculaire"], indications:["insomnie","anxiete","irritabilite","brulure_superficielle","acne"], age_min:7, ci:{grossesse:true, allaitement:true, asthme:"avis_allergologue"}, precaution:"Diluer à 50% pour usage sur grande surface cutanée."},
 {id:"lavande_aspic", nom:"Lavande aspic", latin:"Lavandula latifolia", proprietes:["antiprurigineuse","anti-infectieuse","cicatrisante"], indications:["piqures","brulures","mycoses","zona"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", troubles_cardiovasculaires:true}, precaution:"Voie orale réservée aux enfants de 15 ans+ (présence de camphre)."},
 {id:"laurier_noble", nom:"Laurier noble", latin:"Laurus nobilis", proprietes:["antibacterienne","antivirale","fongicide"], indications:["fatigue","desequilibre_nerveux","aphte","chute_cheveux"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true}, precaution:"Peut être allergisante — test cutané préalable recommandé."},
 {id:"helichryse", nom:"Hélichryse (immortelle)", latin:"Helichrysum italicum", proprietes:["anti-hematome","fibrinolytique","cicatrisante"], indications:["bleus","varices","crevasses","acne_rosacee"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", anticoagulants:true, troubles_coagulation:true}, precaution:"Voie orale sur avis médical uniquement. Prudence en cas de traitement anticoagulant."},
 {id:"giroflier", nom:"Giroflier", latin:"Syzygium aromaticum", proprietes:["antivirale","antibacterienne","analgesique_dentaire"], indications:["douleurs_dentaires","digestion","fatigue","coupe_faim"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_hepatique:true, hepatite:true}, precaution:"Fortement irritante pure : toujours diluer avant application cutanée."},
 {id:"gingembre_frais", nom:"Gingembre frais", latin:"Zingiber officinale", proprietes:["tonique","antifatigue","digestive","anti-inflammatoire"], indications:["digestion","libido","constipation","chute_cheveux"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", anticoagulants:true, chirurgie_prevue:true}, precaution:"Éviter avant une intervention chirurgicale ou avec un traitement anticoagulant."},
 {id:"geranium", nom:"Géranium", latin:"Pelargonium x asperum", proprietes:["antibacterienne","cicatrisante","raffermissante"], indications:["mycose_cutanee","cellulite","piqures_insectes","sautes_humeur"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"—"},
 {id:"genevrier", nom:"Genévrier", latin:"Juniperus communis", proprietes:["antidouleur","anti-inflammatoire","drainante"], indications:["arthrite","arthrose","cellulite","retention_eau"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", cancer_hormonodependant:true, insuffisance_renale:true}, precaution:"Ne pas dépasser 8 jours consécutifs (risque de fatiguer les reins)."},
 {id:"gaultherie", nom:"Gaulthérie (wintergreen)", latin:"Gaultheria fragrantissima", proprietes:["anti-inflammatoire","antalgique","antispasmodique"], indications:["entorse","tendinite","courbatures","rhumatismes"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", anticoagulants:true, allergie_aspirine:true}, precaution:"INTERDITE PAR VOIE ORALE. Contre-indiquée en cas d'allergie à l'aspirine/salicylés. Diluer à 25% sur zones larges. Ne jamais appliquer pure sur un hématome récent."},
 {id:"eucalyptus_radie", nom:"Eucalyptus radié", latin:"Eucalyptus radiata", proprietes:["antivirale","decongestionnant_respiratoire","expectorante"], indications:["infections_orl","otite","nez_bouche","defenses_naturelles"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", anticoagulants:true}, precaution:"Diluer à 50% pour les enfants."},
 {id:"thym_thymol", nom:"Thym à thymol", latin:"Thymus zygis thymoliferum", proprietes:["antibacterienne_majeure","antifongique","antiparasitaire"], indications:["bronchite","etat_grippal","verrues","convalescence"], age_min:15, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", gastrite:true, ulcere:true, insuffisance_hepatique:true, hepatite:true}, precaution:"Dermocaustique : max 5% en dilution. Voie orale réservée à 15 ans+, faible dose."},
 {id:"thym_thujanol", nom:"Thym à thujanol", latin:"Thymus vulgaris thujanoliferum", proprietes:["antibacterienne","antivirale","tonique_hepatique"], indications:["maux_hiver","fatigue_immunitaire","foie_paresseux"], age_min:12, ci:{grossesse:true, allaitement:true, asthme:"avis_allergologue"}, precaution:"Bien tolérée, diluer par précaution avant application cutanée."},
 {id:"thym_linalol", nom:"Thym à linalol", latin:"Thymus vulgaris linaloliferum", proprietes:["antiseptique","antifongique","vermifuge"], indications:["orl","mycose","gingivite","fatigue"], age_min:7, ci:{grossesse:true, allaitement:true, asthme:"avis_allergologue"}, precaution:"Diluer par précaution avant application sur la peau."},
 {id:"tea_tree", nom:"Tea tree (arbre à thé)", latin:"Melaleuca alternifolia", proprietes:["anti-infectieuse_majeure","antifongique","immunomodulante"], indications:["acne","mal_gorge","poux","immunite"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true}, precaution:"Diluer de préférence, sauf usage très localisé stop-bouton."},
 {id:"sauge_sclaree", nom:"Sauge sclarée", latin:"Salvia sclarea", proprietes:["oestrogene_mimetique","regulatrice_sebum","antitranspirante"], indications:["syndrome_premenstruel","menopause","bouffees_chaleur","transpiration"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", cancer_hormonodependant:true, mastose:true}, precaution:"Ne pas associer à une consommation d'alcool (nausées, migraines). Ne pas confondre avec la sauge officinale."},
 {id:"sarriette_montagnes", nom:"Sarriette des montagnes", latin:"Satureja montana", proprietes:["anti-infectieuse_majeure","immunostimulante","antiparasitaire"], indications:["angine","cystite","verrue_plantaire","acne_severe"], age_min:15, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", gastrite:true, ulcere:true, hepatite:true, insuffisance_hepatique:true}, precaution:"Non dénuée de toxicité : max 2 semaines d'affilée, jamais pure, voie orale 15 ans+."},
 {id:"sapin_siberie", nom:"Sapin de Sibérie", latin:"Abies sibirica", proprietes:["antispasmodique","decongestionnant_respiratoire","antifatigue"], indications:["spasmes_intestinaux","toux","contractures_musculaires"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true}, precaution:"Toujours diluée avant application (autant d'huile végétale que d'HE)."},
 {id:"santal_ncaledonie", nom:"Santal de Nouvelle-Calédonie", latin:"Santalum austrocaledonicum", proprietes:["sedative","regenerante","antimycosique"], indications:["anxiete","peau_devitalisee","oedeme_lymphatique","sautes_humeur"], age_min:18, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Réservée à l'adulte."},
 {id:"romarin_verbenone", nom:"Romarin à verbénone", latin:"Rosmarinus officinalis verbenoniferum", proprietes:["drainante_hepatique","regenerante_cutanee","mucolytique"], indications:["detox_hepatique","fatigue_nerveuse","bronchite"], age_min:15, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", troubles_cardiovasculaires:true}, precaution:"Pure, ne pas respirer plus de 3 minutes. Voie orale limitée à 7 jours (cétones)."},
 {id:"romarin_cineole", nom:"Romarin à cinéole", latin:"Rosmarinus officinalis cineoliferum", proprietes:["antiseptique_respiratoire","anti-inflammatoire","tonique_cognitif"], indications:["sinusite","bronchite","herpes_labial","fatigue_memoire"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Ne pas utiliser à forte dose ni sur période prolongée."},
 {id:"romarin_camphre", nom:"Romarin à camphre", latin:"Rosmarinus officinalis camphoriferum", proprietes:["stimulante","digestive","antalgique_musculaire"], indications:["digestion","courbatures","cellulite","tonus"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", troubles_cardiovasculaires:true}, precaution:"Voie orale adulte, faible dose, courte durée."},
 {id:"ravintsara", nom:"Ravintsara", latin:"Cinnamomum camphora cineoliferum", proprietes:["antivirale_puissante","anti-infectieuse","tonique"], indications:["rhume","grippe","herpes_labial","fatigue_immunitaire"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", anticoagulants:true}, precaution:"Diluer à 50% pour les enfants."},
 {id:"pin_sylvestre", nom:"Pin sylvestre", latin:"Pinus sylvestris", proprietes:["anti-inflammatoire","antiseptique_respiratoire","tonique"], indications:["toux","fatigue","jambes_lourdes","allergies_respiratoires"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true}, precaution:"Toujours diluée avant application cutanée."},
 {id:"petit_grain_bigarade", nom:"Petit grain bigarade", latin:"Citrus aurantium ssp amara", proprietes:["relaxante","sedative","antispasmodique"], indications:["troubles_sommeil","hyperactivite","regles_douloureuses","transpiration"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Diluer avant toute application cutanée."},
 {id:"patchouli", nom:"Patchouli", latin:"Pogostemon cablin", proprietes:["calmante","anti-irritante","tonique_veineuse"], indications:["couperose","varices","stress","pellicules"], age_min:18, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", cancer_hormonodependant:true, mastose:true}, precaution:"Réservée à l'adulte. Ne pas s'exposer au soleil après application."},
 {id:"pamplemousse", nom:"Pamplemousse", latin:"Citrus x paradisi", proprietes:["drainante","diuretique","detoxifiante"], indications:["cellulite","retention_eau","assainissement_air"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true, insuffisance_hepatique:true}, photosensibilisant:true, precaution:"PHOTOSENSIBILISANTE : attendre 24h avant exposition solaire."},
 {id:"palmarosa", nom:"Palmarosa", latin:"Cymbopogon martinii", proprietes:["antibacterienne","antivirale","stimulante_cutanee"], indications:["infections_orl_enfant","mycose_cutanee","peau_seche","transpiration"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue"}, precaution:"Diluer avant application cutanée."},
 {id:"origan_compact", nom:"Origan compact", latin:"Origanum compactum", proprietes:["anti-infectieuse_majeure","antivirale","antiparasitaire"], indications:["diarrhee","fatigue","grippe","convalescence"], age_min:15, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", gastrite:true, ulcere:true, hepatite:true, insuffisance_hepatique:true}, precaution:"Non dénuée de toxicité : max 2 semaines, jamais pure, voie orale 15 ans+."},
 {id:"orange_douce", nom:"Orange douce", latin:"Citrus sinensis", proprietes:["calmante","sedative","digestive"], indications:["anxiete","troubles_sommeil","piqures_insectes"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", insuffisance_renale:true, insuffisance_hepatique:true}, photosensibilisant:true, precaution:"PHOTOSENSIBILISANTE : attendre 24h avant exposition solaire."},
 {id:"niaouli", nom:"Niaouli (sauvage)", latin:"Melaleuca viridiflora", proprietes:["immunomodulante","cicatrisante","decongestionnant_respiratoire"], indications:["sinusite","rhinite","brulure_superficielle","otite"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", cancer_hormonodependant:true, mastose:true, anticoagulants:true}, precaution:"Respecter scrupuleusement les doses prescrites."},
 {id:"ylang_ylang", nom:"Ylang-ylang (distillation complète)", latin:"Cananga odorata", proprietes:["antifatigue","antirhumatismale","revitalisante_cutanee"], indications:["stress","insomnie","libido","cheveux_ternes"], age_min:7, ci:{grossesse:true, allaitement:true, epilepsie:true, asthme:"avis_allergologue", allergie_aspirine:true}, precaution:"—"},
];

const HUILES_VEGETALES = [
 {id:"rose_musquee", nom:"Rose musquée", latin:"Rosa rubiginosa/canina", proprietes:["cicatrisante","regenerante","anti-age"], indications:["cicatrices","rides","taches_brunes"], comedogenicite:3, ci:{peau_acneique:"deconseillee", allergie:true}},
 {id:"ricin", nom:"Ricin", latin:"Ricinus communis", proprietes:["fortifiante_ongles_cils","adoucissante"], indications:["ongles_cassants","chute_cheveux"], comedogenicite:1, ci:{}, precaution:"Usage externe uniquement, ne pas ingérer."},
 {id:"nigelle", nom:"Nigelle (cumin noir)", latin:"Nigella sativa", proprietes:["anti-inflammatoire","regenerante","antiallergique"], indications:["peau_acneique","eczema","psoriasis","allergie_cutanee"], comedogenicite:1, ci:{}, precaution:"Voie orale : max 2 ml/jour."},
 {id:"millepertuis", nom:"Millepertuis (macérat huileux)", latin:"Hypericum perforatum", proprietes:["calmante","antiprurigineuse","reparatrice"], indications:["urticaire","herpes_labial","brulure","nevralgie"], comedogenicite:0, ci:{photosensibilisant:true}, precaution:"PHOTOSENSIBILISANT : ne pas exposer au soleil pendant/après application (7 jours après arrêt)."},
 {id:"macadamia", nom:"Macadamia", latin:"Macadamia integrifolia", proprietes:["nourrissante","antiradicalaire","tonique_lymphatique"], indications:["vergetures","cellulite","peau_seche"], comedogenicite:2, ci:{allergie_fruits_coque:true}},
 {id:"karite", nom:"Karité (beurre)", latin:"Butyrospermum parkii", proprietes:["protectrice","cicatrisante","anti-age"], indications:["peaux_tres_seches","gercures","levres_abimees"], comedogenicite:0, ci:{peau_acneique:"deconseillee"}},
 {id:"jojoba", nom:"Jojoba (cire liquide)", latin:"Simmondsia chinensis", proprietes:["regulatrice_sebum","hydratante","nourrissante"], indications:["peau_grasse_deshydratee","cheveux_secs_ou_gras"], comedogenicite:0, ci:{}},
 {id:"figue_barbarie", nom:"Figue de Barbarie", latin:"Opuntia ficus indica", proprietes:["antioxydante","regenerante","tonique_cutanee"], indications:["peau_atone","psoriasis","eczema","peau_deshydratee"], comedogenicite:1, ci:{}},
 {id:"coco", nom:"Coco", latin:"Cocos nucifera", proprietes:["protectrice","antibacterienne","hydratante"], indications:["peau_phaneres_agresses","psoriasis","soin_capillaire"], comedogenicite:4, ci:{peau_acneique:"deconseillee"}},
 {id:"chanvre", nom:"Chanvre", latin:"Cannabis sativa", proprietes:["antirougeurs","anti-irritant","reparatrice"], indications:["couperose","peau_ultra_reactive","psoriasis"], comedogenicite:0, ci:{}, precaution:"Ne contient pas de THC — sans effet psychoactif."},
 {id:"calophylle", nom:"Calophylle", latin:"Calophyllum inophyllum", proprietes:["tonique_veineuse","anti-inflammatoire","cicatrisante"], indications:["jambes_lourdes","varices","couperose","arthrose"], comedogenicite:1, ci:{allergie:true, anticoagulants:true}},
 {id:"arnica", nom:"Arnica (macérat huileux)", latin:"Arnica montana", proprietes:["antalgique","anti-inflammatoire","anticontusions"], indications:["bleus","courbatures","entorse","arthrose"], comedogenicite:0, ci:{grossesse:true, allaitement:true, age_min:12, allergie_asteracees:true, anticoagulants:true}, precaution:"Usage externe uniquement, 7 jours max, ne pas appliquer sur peau lésée."},
 {id:"argan", nom:"Argan", latin:"Argania spinosa", proprietes:["revitalisante","nourrissante","anti-age"], indications:["peau_mature","cheveux_devitalises","ongles"], comedogenicite:0, ci:{allergie_fruits_coque:"faible"}},
 {id:"amande_douce", nom:"Amande douce", latin:"Prunus amygdalus", proprietes:["adoucissante","apaisante","reparatrice"], indications:["peau_sensible_irritee","eczema","gercures"], comedogenicite:2, ci:{allergie_fruits_coque:true}},
 {id:"noyau_abricot", nom:"Noyau d'abricot", latin:"Prunus armeniaca", proprietes:["illuminatrice","tonifiante","antiradicalaire"], indications:["peau_terne","teint_fatigue"], comedogenicite:2, ci:{allergie:"mineure"}},
];

const HYDROLATS = [
 {id:"rose_damas", nom:"Rose de Damas", latin:"Rosa damascena", proprietes:["illuminatrice","regenerante","astringente"], indications:["peau_terne","susceptibilite","fatigue_nerveuse"], age_min:3},
 {id:"fleur_oranger", nom:"Fleur d'oranger", latin:"Citrus aurantium ssp amara", proprietes:["equilibrante","apaisante","revitalisante"], indications:["peau_seche_irritee","desequilibre_nerveux","spasmes_intestinaux"], age_min:3},
 {id:"lavande_vraie_hydrolat", nom:"Lavande vraie", latin:"Lavandula angustifolia", proprietes:["purifiante","regenerante","apaisante"], indications:["peau_mixte_grasse","cheveux_gras","demangeaisons"], age_min:3},
 {id:"hamamelis", nom:"Hamamélis", latin:"Hamamelis virginiana", proprietes:["decongestionnant","astringent","anti-inflammatoire"], indications:["rosacee","couperose","urticaire"], age_min:3, ci:{lactones_allergisantes:true}, precaution:"Test au pli du coude recommandé avant utilisation."},
 {id:"geranium_hydrolat", nom:"Géranium", latin:"Pelargonium graveolens", proprietes:["purifiante","antiseptique","astringente"], indications:["peau_tiraillee","imperfections","coup_de_blues"], age_min:3},
 {id:"bleuet", nom:"Bleuet", latin:"Centaurea cyanus", proprietes:["decongestionnant_yeux","apaisant","anti-inflammatoire"], indications:["poches_cernes","yeux_fatigues","conjonctivite"], age_min:3},
];

/* --------------------------------------------------------------------------
   Filtre de sécurité : écarte toute huile incompatible avec le profil de
   la cliente AVANT toute proposition. Le silence sur un champ = à vérifier,
   jamais "c'est sûr" (cf. principe du doute).
   Profil attendu : { grossesse:bool, allaitement:bool, age:number,
     cancer_hormonodependant:bool, epilepsie:bool, asthme:bool,
     anticoagulants:bool, insuffisance_renale:bool, insuffisance_hepatique:bool,
     allergies_he:bool }
   -------------------------------------------------------------------------- */
function aromatherapieFiltrer(liste, profil) {
  return liste.filter(item => {
    const ci = item.ci || {};
    if (profil.allergies_he) return false; // allergie HE connue -> on n'en propose aucune
    if ((profil.grossesse || profil.allaitement) && (ci.grossesse || ci.allaitement)) return false;
    if (profil.cancer_hormonodependant && (ci.cancer_hormonodependant || ci.mastose)) return false;
    if (profil.epilepsie && ci.epilepsie) return false;
    if (profil.asthme && ci.asthme === true) return false; // "avis_allergologue" = signaler, pas exclure d'office
    if (profil.anticoagulants && ci.anticoagulants) return false;
    if (profil.insuffisance_renale && ci.insuffisance_renale) return false;
    if (profil.insuffisance_hepatique && (ci.insuffisance_hepatique || ci.hepatite)) return false;
    if (item.age_min && profil.age && profil.age < item.age_min) return false;
    return true;
  });
}

if (typeof module !== 'undefined') {
  module.exports = { HUILES_ESSENTIELLES, HUILES_VEGETALES, HYDROLATS, aromatherapieFiltrer };
}
